Update action.yml

diff --git a/actions/delete-token/action.yml b/actions/delete-token/action.yml
--- a/actions/delete-token/action.yml
+++ b/actions/delete-token/action.yml
@@ -48,12 +48,13 @@ runs:
 
             $response = Invoke-RestMethod -Method Delete -Uri $url -Headers $headers
 
-            if ($null -eq $response -or $LASTEXITCODE -ne 0) {
-                echo "Delete request failed or returned no response."
-                exit 1
-            } else {
-                echo "Token $tokenId was successfully deleted."
-            }
+            # so far docs dont show any response, so leaving this commented out
+            # if ($response.StatusCode -ne 200) {
+            #   echo "Delete request failed with status code $($response.StatusCode)."
+            #   exit 1
+            # } else {
+            #     echo "Token $tokenId was successfully deleted."
+            # }
         }
         catch {
             echo "Error: $($_.Exception.Message)"
